### PR TITLE
support Windows10 14316

### PR DESCRIPTION
**Pull request by jp1017**

### CODE REVIEW

**Comment by satnam6502** [comment]
Thank you kindly for this pull request. It would be **great** to have Window 10 support for building ReDex. It's very interesting to see that your approach involves using the new capability of running bash natively on Windows. Right now we would like to focus on getting a solid development experience under OS X and Linux so while bash support remains in preview I think we should wait. Have you managed to get ReDex to successfully run with Windows 10 bash preview?

**Comment by satnam6502** [comment]
Until we can be sure of supporting a viable native Windows experience perhaps it is worth considering virtualization options like VirtualBox or using Docker containers.

**Comment by jp1017** [comment]
Yes, I make it on Win10 Preview using bash.    https://github.com/facebook/redex/issues/11

**Comment by brian512** [comment]
I got this error,
qq 20160418120708

and I found this msg in redex.py.
qq 20160418120656

how should I deal with it ? thx

**Pull request closed without merging**
