### PR TITLE
Vcpkg mman dependency

### PR DESCRIPTION
**Pull request by diegoflassa**
For Windows 10 (64-bit) Builds - "mman install" related changes:

-Added "/.vs/" and "/build-cmake/" folders to gitignore
-Added "vcpkg mman install" instruction to the README
-Added platform verification for mman header inclusion

### CODE REVIEW

**Comment by minjang** [comment]
@diegoflassa Thanks for the contribution. I haven't tested Windows build for a while. I'm wondering why `mman` is needed?

**Comment by diegoflassa** [comment]
Hy!

For now i'm trying to get the project to compile in a Win 10 (x64) environment, following the provided instructions. The reason for the changes is that the header "mman.h" is declared in the "libresource/RedexResources.cpp" file.

>>Line 21 #include <sys/mman.h>

It is not something included by me in this file, nor in any other that may eventually have it, so i assumed that is a required package, and changed the instructions accordingly. I don't know exactly what it is needed for, but i will take a look, if further information is needed.

**Comment by diegoflassa** [comment]
The "#include <sys/mman.h>" was introduced in the "libresource/RedexResources.cpp" file in this commit

"Extract helper methods for mapping files and serialization"
https://github.com/facebook/redex/commit/b39e7ae14ce3cac79c855b467f9374dbcf15dbb4

**Comment by minjang** [comment]
@diegoflassa Thanks so much! I will import this diff. And if you see other compile errors in Windows 10, please submit patches. We actually don't have CI build system for Windows. So it's very easy to be broken.

**Pull request closed without merging**
