### PR TITLE
Make autotools build system build redexdump

### PR DESCRIPTION
**Pull request by dcolascione**
Now make at toplevel will build redexdump as well

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request.  As you may know, we require contributors to sign our Contributor License Agreement, and we don't seem to have you on file and listed as active anymore.  In order for us to review and merge your code, please email cla@fb.com with your details so we can update your status.

**Comment by dcolascione** [comment]
Oh, come on. Really?

**Comment by bertmaher** [comment]
Bah, sorry, I can't even get internal phabricator to merge your pull request without the CLA :-p

**Comment by facebook-github-bot-6** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Pull request closed without merging**
