### PR TITLE
App for ProGuard example

### PR DESCRIPTION
**Pull request by satnam6502**
Example of how to specify simple ProGuard rules to Redex.

### CODE REVIEW

**Comment by satnam6502** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/172224906510775/int_phab) to review.

**Comment by satnam6502** [comment]
@facebook-github-bot import

**Comment by satnam6502** [comment]
Created to address #129

**Comment by facebook-github-bot-8** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/172224906510775/int_phab) to review.

**Comment by satnam6502** [comment]
@facebook-github-bot import

**Comment by facebook-github-bot-5** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/172224906510775/int_phab) to review.

**Pull request closed without merging**
